#language: go
sudo: required
dist: trusty

services:
  - docker

#go: 1.8.x

before_install:
  - sudo sh -c 'echo "deb https://apt.dockerproject.org/repo ubuntu-$(lsb_release -cs) main" > /etc/apt/sources.list.d/docker.list'
  - curl -fsSL https://apt.dockerproject.org/gpg | sudo apt-key add -
  - sudo apt-key fingerprint 58118E89F3A912897C070ADBF76221572C52609D
  - sudo apt-get update
  - sudo apt-get -y install "docker-engine=1.13.1-0~ubuntu-$(lsb_release -cs)"
  - sudo service docker restart
  - sudo docker version

script:
  - docker run -itd -p 80:80 --name=nginx nginx
  - curl localhost
  - ip=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' nginx)
  - curl $ip
